/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    MyTestCpm: typeof import('./src/components/my-test-cpm.vue')['default']
    OtherCpm: typeof import('./src/components/otherCpm.vue')['default']
    RgyxWorkPoint: typeof import('./src/components/rgyx-work-point.vue')['default']
  }
}
